import { type FormEvent, useState } from "react";
import { ArrowDown, ArrowUp, ExternalLink, Plus } from "lucide-react";
import { AdminSectionHeader } from "../components/AdminSectionHeader";
import { useStoreConfigStore } from "../../store/storeConfigStore";
import { useCategoryStore } from "../../store/categoryStore";
import { useProductStore } from "../../store/productStore";
import type { StoreConfig } from "../../types/storeConfig";
import type { Category } from "../../types/category";
import { slugify } from "../../utils/normalization";

const field = (label: string, value: string | number, onChange: (value: string) => void, type = "text") => <label className="admin-field"><span>{label}</span><input type={type} value={value} onChange={(e) => onChange(e.target.value)} /></label>;
const toggle = (label: string, checked: boolean, onChange: (checked: boolean) => void) => <label className="admin-check"><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} /><span>{label}</span></label>;
const homeSectionLabel = (type: string) => ({ hero: "Portada", categories: "Categorías", "featured-products": "Nuevos modelos", "brand-statement": "Nuestra confección", campaign: "Colección editorial", "best-sellers": "Modelos destacados", benefits: "Información de compra", social: "Instagram y redes" }[type] ?? type);
export function AdminStore() {
  const persisted = useStoreConfigStore((s) => s.config), setConfig = useStoreConfigStore((s) => s.setConfig);
  const [config, setLocal] = useState<StoreConfig>(persisted), [saved, setSaved] = useState(false);
  const categories = useCategoryStore((s) => s.categories), saveCategory = useCategoryStore((s) => s.save), moveCategory = useCategoryStore((s) => s.move), products = useProductStore((s) => s.products);
  const patch = <K extends keyof StoreConfig>(key: K, value: StoreConfig[K]) => setLocal((c) => ({ ...c, [key]: value }));
  const save = (e: FormEvent) => { e.preventDefault(); setConfig(config); setSaved(true); window.setTimeout(() => setSaved(false), 1800); };
  const addCategory = () => { const name = window.prompt("Nombre de la categoría"); if (!name?.trim()) return; const id = crypto.randomUUID(); saveCategory({ id, name: name.trim(), slug: slugify(name), description: "", image: "", active: true, featured: true, sortOrder: categories.length }); };
  const updateCategory = (category: Category, change: Partial<Category>) => saveCategory({ ...category, ...change });
  return <div className="admin-module"><AdminSectionHeader eyebrow="STOREFRONT CONTROL" title="Tienda" description="Gestiona lo que ve el cliente sin editar React." action={<a className="admin-primary-button" href="/" target="_blank" rel="noreferrer"><ExternalLink size={16}/> Ver tienda</a>} />
    <form onSubmit={save} className="admin-business-form">
      <section className="admin-card"><h2>Identidad</h2><div className="admin-form-grid">{field("Nombre", config.identity.name, (v) => patch("identity", { ...config.identity, name: v }))}{field("Nombre corto", config.identity.shortName, (v) => patch("identity", { ...config.identity, shortName: v }))}{field("Tagline", config.identity.tagline, (v) => patch("identity", { ...config.identity, tagline: v }))}{field("Logo URL/path", config.identity.logo, (v) => patch("identity", { ...config.identity, logo: v }))}{field("Favicon", config.identity.favicon ?? "", (v) => patch("identity", { ...config.identity, favicon: v }))}{Object.entries(config.identity.colors).map(([key,value]) => field(`Color ${key}`, value, (v) => patch("identity", { ...config.identity, colors: { ...config.identity.colors, [key]: v } }), "color"))}</div></section>
      <section className="admin-card"><h2>Contacto y WhatsApp</h2><div className="admin-form-grid">{field("WhatsApp", config.contact.whatsapp, (v) => patch("contact", { ...config.contact, whatsapp: v }))}{field("Email", config.contact.email, (v) => patch("contact", { ...config.contact, email: v }), "email")}{field("Ciudad", config.contact.city, (v) => patch("contact", { ...config.contact, city: v }))}{field("País", config.contact.country, (v) => patch("contact", { ...config.contact, country: v }))}<label className="admin-field admin-field-wide"><span>Mensaje predeterminado</span><textarea value={config.contact.whatsappMessage} onChange={(e) => patch("contact", { ...config.contact, whatsappMessage: e.target.value })}/></label></div></section>
      <section className="admin-card"><h2>Redes sociales</h2><div className="admin-form-grid">{(["instagram","facebook","tiktok"] as const).map((key) => <div key={key} className="admin-subcard">{toggle(key, config.social[key].enabled, (enabled) => patch("social", { ...config.social, [key]: { ...config.social[key], enabled } }))}{field("URL", config.social[key].url, (url) => patch("social", { ...config.social, [key]: { ...config.social[key], url } }))}{field("Handle", config.social[key].handle ?? "", (handle) => patch("social", { ...config.social, [key]: { ...config.social[key], handle } }))}</div>)}</div></section>
      <section className="admin-card"><h2>Announcement</h2>{toggle("Mostrar barra", config.announcement.enabled, (enabled) => patch("announcement", { ...config.announcement, enabled }))}<div className="admin-form-grid">{field("Texto", config.announcement.text, (text) => patch("announcement", { ...config.announcement, text }))}{field("Texto enlace", config.announcement.linkText, (linkText) => patch("announcement", { ...config.announcement, linkText }))}{field("Ruta", config.announcement.href, (href) => patch("announcement", { ...config.announcement, href }))}</div></section>
      <section className="admin-card"><h2>Hero</h2>{toggle("Hero activo", config.home.hero.enabled, (enabled) => patch("home", { ...config.home, hero: { ...config.home.hero, enabled } }))}<div className="admin-form-grid">{field("Eyebrow", config.home.hero.eyebrow, (eyebrow) => patch("home", { ...config.home, hero: { ...config.home.hero, eyebrow } }))}{field("Título", config.home.hero.title, (title) => patch("home", { ...config.home, hero: { ...config.home.hero, title } }))}{field("Descripción", config.home.hero.description, (description) => patch("home", { ...config.home, hero: { ...config.home.hero, description } }))}{field("Botón principal", config.home.hero.primaryButtonLabel, (primaryButtonLabel) => patch("home", { ...config.home, hero: { ...config.home.hero, primaryButtonLabel } }))}{field("Ruta principal", config.home.hero.primaryButtonHref, (primaryButtonHref) => patch("home", { ...config.home, hero: { ...config.home.hero, primaryButtonHref } }))}{field("Botón secundario", config.home.hero.secondaryButtonLabel ?? "", (secondaryButtonLabel) => patch("home", { ...config.home, hero: { ...config.home.hero, secondaryButtonLabel } }))}{field("Ruta secundaria", config.home.hero.secondaryButtonHref ?? "", (secondaryButtonHref) => patch("home", { ...config.home, hero: { ...config.home.hero, secondaryButtonHref } }))}{field("Imagen escritorio", config.home.hero.image, (image) => patch("home", { ...config.home, hero: { ...config.home.hero, image } }))}{field("Imagen móvil", config.home.hero.mobileImage ?? "", (mobileImage) => patch("home", { ...config.home, hero: { ...config.home.hero, mobileImage } }))}</div></section>
      <section className="admin-card"><h2>Confección FLOES</h2><p>Contenido e imagen del bloque editorial de marca.</p><div className="admin-form-grid">{field("Eyebrow", config.home.brandStory.eyebrow, (eyebrow) => patch("home", { ...config.home, brandStory: { ...config.home.brandStory, eyebrow } }))}{field("Título", config.home.brandStory.title, (title) => patch("home", { ...config.home, brandStory: { ...config.home.brandStory, title } }))}{field("Descripción", config.home.brandStory.description, (description) => patch("home", { ...config.home, brandStory: { ...config.home.brandStory, description } }))}{field("Imagen editorial", config.home.brandStory.image, (image) => patch("home", { ...config.home, brandStory: { ...config.home.brandStory, image } }))}{field("Texto alternativo", config.home.brandStory.imageAlt, (imageAlt) => patch("home", { ...config.home, brandStory: { ...config.home.brandStory, imageAlt } }))}{field("Texto del botón", config.home.brandStory.buttonLabel, (buttonLabel) => patch("home", { ...config.home, brandStory: { ...config.home.brandStory, buttonLabel } }))}{field("Ruta del botón", config.home.brandStory.buttonHref, (buttonHref) => patch("home", { ...config.home, brandStory: { ...config.home.brandStory, buttonHref } }))}</div></section>
      <section className="admin-card"><h2>Estructura pública FLOES</h2><p>Activa y ordena las secciones que aparecen en la tienda.</p><div className="admin-stack">{[...config.home.sections].sort((a,b) => a.sortOrder-b.sortOrder).map((section, index, sorted) => <div className="admin-list-row" key={section.id}>{toggle(homeSectionLabel(section.type), section.enabled, (enabled) => patch("home", { ...config.home, sections: config.home.sections.map((s) => s.id === section.id ? { ...s, enabled } : s) }))}{(section.type === "featured-products" || section.type === "best-sellers") && <>{field("Título", section.title ?? "", (title) => patch("home", { ...config.home, sections: config.home.sections.map((s) => s.id === section.id ? { ...s, title } : s) }))}{field("Descripción", section.description ?? "", (description) => patch("home", { ...config.home, sections: config.home.sections.map((s) => s.id === section.id ? { ...s, description } : s) }))}{field("Límite", section.limit ?? 4, (value) => patch("home", { ...config.home, sections: config.home.sections.map((s) => s.id === section.id ? { ...s, limit: Math.max(1, Math.floor(Number(value) || 1)) } : s) }), "number")}</>}<div><button type="button" disabled={!index} onClick={() => { const other = sorted[index-1]; patch("home", { ...config.home, sections: config.home.sections.map((s) => s.id === section.id ? { ...s, sortOrder: other.sortOrder } : s.id === other.id ? { ...s, sortOrder: section.sortOrder } : s) }) }}><ArrowUp size={15}/></button><button type="button" disabled={index === sorted.length-1} onClick={() => { const other = sorted[index+1]; patch("home", { ...config.home, sections: config.home.sections.map((s) => s.id === section.id ? { ...s, sortOrder: other.sortOrder } : s.id === other.id ? { ...s, sortOrder: section.sortOrder } : s) }) }}><ArrowDown size={15}/></button></div></div>)}</div></section>
      <section className="admin-card"><div className="admin-section-inline"><h2>Navegación</h2><button type="button" className="admin-button" onClick={() => patch("navigation", [...config.navigation, { id: crypto.randomUUID(), label: "Nuevo enlace", href: "/catalogo", enabled: true, sortOrder: config.navigation.length }])}><Plus size={15}/> Añadir</button></div><div className="admin-stack">{[...config.navigation].sort((a,b) => a.sortOrder-b.sortOrder).map((item) => <div className="admin-list-row" key={item.id}>{toggle("", item.enabled, (enabled) => patch("navigation", config.navigation.map((n) => n.id === item.id ? { ...n, enabled } : n)))}{field("Etiqueta", item.label, (label) => patch("navigation", config.navigation.map((n) => n.id === item.id ? { ...n, label } : n)))}{field("Ruta", item.href, (href) => patch("navigation", config.navigation.map((n) => n.id === item.id ? { ...n, href } : n)))}</div>)}</div></section>
      <section className="admin-card"><h2>Comercio</h2><div className="admin-form-grid">{field("Moneda", config.commerce.currency, (currency) => patch("commerce", { ...config.commerce, currency }))}{field("País", config.commerce.country, (country) => patch("commerce", { ...config.commerce, country }))}{field("Texto de envío", config.commerce.shippingText, (shippingText) => patch("commerce", { ...config.commerce, shippingText }))}{field("Costo fijo", config.commerce.shippingCost, (v) => patch("commerce", { ...config.commerce, shippingCost: Math.max(0, Number(v) || 0) }), "number")}</div>{toggle("Envíos", config.commerce.shippingEnabled, (shippingEnabled) => patch("commerce", { ...config.commerce, shippingEnabled }))}{toggle("Checkout web", config.commerce.webCheckoutEnabled, (webCheckoutEnabled) => patch("commerce", { ...config.commerce, webCheckoutEnabled }))}{toggle("Transferencia", config.commerce.paymentMethods.transfer, (transfer) => patch("commerce", { ...config.commerce, paymentMethods: { ...config.commerce.paymentMethods, transfer } }))}{toggle("Efectivo en Guayaquil", config.commerce.paymentMethods.cash, (cash) => patch("commerce", { ...config.commerce, paymentMethods: { ...config.commerce.paymentMethods, cash } }))}{toggle("Botones de WhatsApp", config.commerce.whatsappPurchaseEnabled, (whatsappPurchaseEnabled) => patch("commerce", { ...config.commerce, whatsappPurchaseEnabled }))}</section>
      <section className="admin-card"><h2>SEO</h2><div className="admin-form-grid">{field("Título del sitio", config.seo.siteTitle, (siteTitle) => patch("seo", { ...config.seo, siteTitle }))}{field("Descripción", config.seo.siteDescription, (siteDescription) => patch("seo", { ...config.seo, siteDescription }))}{field("Keywords", config.seo.keywords, (keywords) => patch("seo", { ...config.seo, keywords }))}</div></section>
      <button className="admin-primary-button" type="submit">Guardar configuración</button>{saved && <span role="status">Configuración guardada.</span>}
    </form>
    <section className="admin-card admin-module"><div className="admin-section-inline"><div><h2>Categorías</h2><p>Solo las activas aparecen en el storefront.</p></div><button className="admin-primary-button" type="button" onClick={addCategory}><Plus size={16}/> Crear categoría</button></div><div className="admin-stack">{[...categories].sort((a,b) => a.sortOrder-b.sortOrder).map((category, index) => <div className="admin-list-row" key={category.id}>{field("Nombre", category.name, (name) => updateCategory(category, { name }))}{field("Slug", category.slug, (slug) => updateCategory(category, { slug }))}{field("Descripción", category.description, (description) => updateCategory(category, { description }))}{field("Imagen", category.image, (image) => updateCategory(category, { image }))}{toggle("Activa", category.active, (active) => updateCategory(category, { active }))}{toggle("Destacada", category.featured, (featured) => updateCategory(category, { featured }))}<button type="button" disabled={!index} onClick={() => moveCategory(category.id, -1)}><ArrowUp/></button><button type="button" disabled={index === categories.length-1} onClick={() => moveCategory(category.id, 1)}><ArrowDown/></button>{products.some((p) => p.category.toLowerCase() === category.name.toLowerCase()) && <small>En uso</small>}</div>)}</div></section>
  </div>;
}
