import { type FormEvent, useState } from "react";
import { Plus } from "lucide-react";
import { AdminSectionHeader } from "../components/AdminSectionHeader";
import { useMarketingStore } from "../../store/marketingStore";
import { promotionStatus } from "../../utils/storefront";
import type { Promotion } from "../../types/marketing";
const empty = (): Promotion => ({ id: crypto.randomUUID(), name: "", type: "percentage", value: 0, startAt: "", endAt: "", active: true, scope: "all", targetIds: [], headline: "", description: "" });
export function AdminMarketing() {
  const promotions = useMarketingStore((s) => s.promotions), save = useMarketingStore((s) => s.savePromotion), setActive = useMarketingStore((s) => s.setPromotionActive), [form, setForm] = useState<Promotion | null>(null);
  const submit = (e: FormEvent) => { e.preventDefault(); if (!form?.name.trim()) return; save({ ...form, value: Math.max(0, Number(form.value) || 0) }); setForm(null); };
  return <div className="admin-module"><AdminSectionHeader eyebrow="ADMIN / MARKETING" title="Marketing" description="Promociones derivadas, sin modificar permanentemente el precio del producto." action={<button className="admin-button admin-button-primary" onClick={() => setForm(empty())}><Plus size={16}/> Nueva promoción</button>} />
    {form && <form className="admin-card admin-business-form" onSubmit={submit}><h2>{promotions.some((p) => p.id === form.id) ? "Editar promoción" : "Crear promoción"}</h2><div className="admin-form-grid"><label className="admin-field"><span>Nombre</span><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })}/></label><label className="admin-field"><span>Tipo</span><select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value as Promotion["type"] })}><option value="percentage">Porcentaje</option><option value="fixed">Valor fijo</option><option value="informational">Informativa</option></select></label><label className="admin-field"><span>Valor</span><input type="number" min="0" step="0.01" value={form.value} onChange={(e) => setForm({ ...form, value: Number(e.target.value) })}/></label><label className="admin-field"><span>Alcance</span><select value={form.scope} onChange={(e) => setForm({ ...form, scope: e.target.value as Promotion["scope"] })}><option value="all">Todos</option><option value="category">Categoría</option><option value="product">Producto</option></select></label><label className="admin-field"><span>Inicio</span><input type="datetime-local" value={form.startAt} onChange={(e) => setForm({ ...form, startAt: e.target.value })}/></label><label className="admin-field"><span>Fin</span><input type="datetime-local" value={form.endAt} onChange={(e) => setForm({ ...form, endAt: e.target.value })}/></label><label className="admin-field"><span>IDs objetivo, separados por coma</span><input value={form.targetIds.join(", ")} onChange={(e) => setForm({ ...form, targetIds: e.target.value.split(",").map((x) => x.trim()).filter(Boolean) })}/></label><label className="admin-field"><span>Headline</span><input value={form.headline} onChange={(e) => setForm({ ...form, headline: e.target.value })}/></label></div><label className="admin-field"><span>Descripción</span><textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })}/></label><div className="admin-form-actions"><button className="admin-button" type="button" onClick={() => setForm(null)}>Cancelar</button><button className="admin-button admin-button-primary">Guardar promoción</button></div></form>}
    <section className="admin-card"><div className="admin-stack">{promotions.map((p) => <article className="admin-list-row" key={p.id}><div><strong>{p.name}</strong><p>{p.headline || p.description}</p></div><span className="admin-status">{promotionStatus(p)}</span><span>{p.type === "percentage" ? `${p.value}%` : p.type === "fixed" ? `$${p.value.toFixed(2)}` : "Informativa"}</span><button onClick={() => setActive(p.id, !p.active)}>{p.active ? "Desactivar" : "Activar"}</button><button onClick={() => setForm(p)}>Editar</button></article>)}{!promotions.length && <p>No hay promociones configuradas.</p>}</div></section>
    <section className="admin-card"><h2>Cupones</h2><p>La estructura persistente está preparada. La aplicación en checkout queda pendiente para no comprometer la estabilidad del flujo de pedidos.</p></section>
  </div>;
}
